//
//  AuthenticationInterfaces.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol AuthenticationWireframeInterface: WireframeInterface {
  func navigateHome()
}

protocol AuthenticationViewInterface: ViewInterface {
}

protocol AuthenticationPresenterInterface: PresenterInterface {
  func shouldNavigate(_ userName: String)
}

protocol AuthenticationInteractorInterface: InteractorInterface {
  func saveUserName(_ userName: String)
}
