//
//  AuthenticationPresenter.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AuthenticationPresenter {
    
    // MARK: - Private properties -

    private unowned let view: AuthenticationViewInterface
    private let interactor: AuthenticationInteractorInterface
    private let wireframe: AuthenticationWireframeInterface

    // MARK: - Lifecycle -

    init(view: AuthenticationViewInterface, interactor: AuthenticationInteractorInterface, wireframe: AuthenticationWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension AuthenticationPresenter: AuthenticationPresenterInterface {
  func shouldNavigate(_ userName: String) {
    wireframe.navigateHome()
    interactor.saveUserName(userName)
  }
}
