//
//  AuthenticationWireframe.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AuthenticationWireframe: BaseWireframe<AuthenticationViewController> {

  // MARK: - Private properties -

  private let storyboard = UIStoryboard(name: "Authentication", bundle: nil)

  // MARK: - Module setup -

  init() {
    let moduleViewController = storyboard.instantiateViewController(ofType: AuthenticationViewController.self)
    super.init(viewController: moduleViewController)

    let interactor = AuthenticationInteractor()
    let presenter = AuthenticationPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
    moduleViewController.presenter = presenter
  }
}

// MARK: - Extensions -

extension AuthenticationWireframe: AuthenticationWireframeInterface {
  func navigateHome() {
    navigationController?.setRootWireframe(HomeWireframe())
  }
}
