//
//  AuthenticationInteractor.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AuthenticationInteractor {
  let userService: UserDefaultsService

  init(userService: UserDefaultsService = .shared) {
    self.userService = userService
  }
}

// MARK: - Extensions -

extension AuthenticationInteractor: AuthenticationInteractorInterface {
  func saveUserName(_ userName: String) {
    userService.setUserName(userName)
  }
}
