//
//  HomePresenter.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomePresenter {
  
  static let galatasarayLegends = GalatasarayLegendsData()
  static let europeanCinema = EuropeanCinemaData()
  
  // MARK: - Private properties -
  
  private unowned let view: HomeViewInterface
  private let interactor: HomeInteractorInterface
  private let wireframe: HomeWireframeInterface
  
  // MARK: - Lifecycle -
  
  init(view: HomeViewInterface, interactor: HomeInteractorInterface, wireframe: HomeWireframeInterface) {
    self.view = view
    self.interactor = interactor
    self.wireframe = wireframe
  }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {
  func shouldNavigateToQuestions(_ category: Dictionary<String, Bool>) {
    wireframe.navigateToQuestions(category)
  }
  
  func pushData(_ category: Dictionary<String, Bool>) {
    interactor.saveQuestions(category)
  }
}
