//
//  HomeInterfaces.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeWireframeInterface: WireframeInterface {
  func navigateToQuestions(_ category: Dictionary<String, Bool>)
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
  func pushData(_ category: Dictionary<String, Bool>)
  func shouldNavigateToQuestions(_ category: Dictionary<String, Bool>)
}

protocol HomeInteractorInterface: InteractorInterface {
  func saveQuestions(_ category: Dictionary<String, Bool>)
}
