//
//  HomeWireframe.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeWireframe: BaseWireframe<HomeViewController> {

  // MARK: - Private properties -

  private let storyboard = UIStoryboard(name: "Home", bundle: nil)

  // MARK: - Module setup -

  init() {
    let moduleViewController = storyboard.instantiateViewController(ofType: HomeViewController.self)
    super.init(viewController: moduleViewController)

    let interactor = HomeInteractor()
    let presenter = HomePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
    moduleViewController.presenter = presenter
  }
}

// MARK: - Extensions -

extension HomeWireframe: HomeWireframeInterface {
  func navigateToQuestions(_ category: Dictionary<String, Bool>) {
    navigationController?.setRootWireframe(QuestionsWireframe(), animated: true)
  }
}
