//
//  HomeInteractor.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeInteractor {

  let context = CoreDataService.shared.context
}



// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {

  func saveQuestions(_ category: Dictionary<String, Bool>) {
    let user = User(context: self.context)
    user.selectedCategory = category
    do {
      try context.save()
    }
    catch {
      print(error.localizedDescription)
    }
  }

}
