//
//  OnboardingViewController.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class OnboardingViewController: UIViewController, UITextFieldDelegate {

  // MARK: - Public properties -

  @IBOutlet weak var gradientView: UIView!
  @IBOutlet weak var appName: UILabel!
  @IBOutlet weak var saveButton: UIButton!
  @IBOutlet weak var userNameField: UITextField!

  private var userName: String = ""
  var presenter: OnboardingPresenterInterface!

  // MARK: - Lifecycle -

  override func viewDidLoad() {
    super.viewDidLoad()
    setupUI()
    setupTextField()
  }

  private func setupUI() {
    appName.text = "Face Answer"
    userNameField.placeholder = "Enter a username"
    saveButton.setTitle("Save Username", for: .normal)
    saveButton.setTitleColor(.darkText, for: .normal)
  }

  private func setupTextField() {
    userNameField.delegate = self
    userNameField.keyboardType = .asciiCapable
    userNameField.returnKeyType = .done
    userNameField.enablesReturnKeyAutomatically = true
  }

  func textFieldShouldReturn(_ textField: UITextField) -> Bool {
    userNameField.resignFirstResponder()
    return true
  }

  private func showAlert() {
    let alert = UIAlertController(title: "Empty Username", message: "Please fill a valid username between 2-15 characters.", preferredStyle: .actionSheet)
    let alertAction = UIAlertAction(title: "OK", style: .default)
    alert.addAction(alertAction)
    present(alert, animated: true, completion: nil)
  }
}

// MARK: - Extensions -

extension OnboardingViewController: OnboardingViewInterface {
  @IBAction func onButtonClick(_ sender: Any) {
    if userNameField.text?.trimmingCharacters(in: .whitespacesAndNewlines) == "" || userNameField.text!.count < 2 || userNameField.text!.count > 15 {
      showAlert()
    } else {
      self.userName = userNameField.text ?? ""
      presenter.shouldNavigate(userName)
    }
  }
}


