//
//  OnboardingInterfaces.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol OnboardingWireframeInterface: WireframeInterface {
}

protocol OnboardingViewInterface: ViewInterface {
}

protocol OnboardingPresenterInterface: PresenterInterface {
}

protocol OnboardingInteractorInterface: InteractorInterface {
}
