//
//  OnboardingInteractor.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class OnboardingInteractor {
}

// MARK: - Extensions -

extension OnboardingInteractor: OnboardingInteractorInterface {
}
