//
//  OnboardingViewController.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class OnboardingViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: OnboardingPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension OnboardingViewController: OnboardingViewInterface {
}
