//
//  OnboardingWireframe.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class OnboardingWireframe: BaseWireframe<OnboardingViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Onboarding", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: OnboardingViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = OnboardingInteractor()
        let presenter = OnboardingPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension OnboardingWireframe: OnboardingWireframeInterface {
}
