//
//  OnboardingInterfaces.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol OnboardingWireframeInterface: WireframeInterface {
  func navigateHome()
}

protocol OnboardingViewInterface: ViewInterface {
}

protocol OnboardingPresenterInterface: PresenterInterface {
  func shouldNavigate(_ userName: String)
}

protocol OnboardingInteractorInterface: InteractorInterface {
  func saveUserName(_ userName: String)
}
