//
//  OnboardingInteractor.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class OnboardingInteractor {
  let userService: UserService

  init(userService: UserService = .shared) {
    self.userService = userService
  }
}

// MARK: - Extensions -

extension OnboardingInteractor: OnboardingInteractorInterface {
  func saveUserName(_ userName: String) {
    userService.setUserName(userName)
  }
}
