//
//  QuestionsWireframe.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class QuestionsWireframe: BaseWireframe<QuestionsViewController> {
  
  // MARK: - Private properties -
  
  private let storyboard = UIStoryboard(name: "Questions", bundle: nil)
  
  // MARK: - Module setup -
  
  init() {
    let moduleViewController = storyboard.instantiateViewController(ofType: QuestionsViewController.self)
    super.init(viewController: moduleViewController)
    
    let interactor = QuestionsInteractor()
    let presenter = QuestionsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
    moduleViewController.presenter = presenter
  }
}

// MARK: - Extensions -

extension QuestionsWireframe: QuestionsWireframeInterface {
  func navigateToResults() {
    navigationController?.setRootWireframe(ResultsWireframe(), animated: true)
  }
}
