//
//  QuestionsInterfaces.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol QuestionsWireframeInterface: WireframeInterface {
  func navigateToResults()
}

protocol QuestionsViewInterface: ViewInterface {
  func getUserData() 
}

protocol QuestionsPresenterInterface: PresenterInterface {
  func getSelectedUserData() -> Dictionary<String, Bool>
  func setSelectedUserScore(_ score: Int64)
  func navigateToResults()
//  func updateAllScores(_ score: Int64)
}

protocol QuestionsInteractorInterface: InteractorInterface {
  func fetchData() -> Dictionary<String, Bool> 
  func saveScore(_ score: Int64)
//  func addScoreToAll(_ score: Int64)
}
