//
//  QuestionsViewController.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class QuestionsViewController: HeadGesture {

  // MARK: - Public properties -

  @IBOutlet weak var scoreLabel: UILabel!
  @IBOutlet weak var timerLabel: UILabel!
  @IBOutlet weak var questionLabel: UILabel!

  weak var countdownTimer: Timer?
  var presenter: QuestionsPresenterInterface!
  var remainingTime = 10
  var selectedCategory: Dictionary<String, Bool>?
  var keysArray: [String] = []
  var valuesArray: [Bool] = []
  var currentIndex = 0

  // MARK: - Lifecycle -

  override func viewDidLoad() {
    super.viewDidLoad()
    scoreLabel.text = "Score: 100"
    timerLabel.text = "TIME STARTS NOW!"
    getUserData()
    keysArray = Array(selectedCategory!.keys)
    valuesArray = Array(selectedCategory!.values)
    updateQuestion()
    setupCamera()
    startTimer()
  }

  override func startTimer() {
    countdownTimer = Timer.scheduledTimer(timeInterval: 1,
                                      target: self,
                                      selector: #selector(updateUIHG),
                                      userInfo: nil,
                                      repeats: true)
  }

  override func stopTimer() {
    countdownTimer?.invalidate()
    countdownTimer = nil
    DispatchQueue.main.async {
      self.timerLabel.text = ""
      self.questionLabel.text = ""
    }
  }

  func updateQuestion() {
    guard currentIndex < keysArray.count else {
      // If all keys have been displayed, reset to the first key
      currentIndex = 0
      return
    }
    let currentKey = keysArray[currentIndex]
    questionLabel.text = "\(currentKey)"
    currentIndex += 1
  }

  override func handleHeadMovement(answer: Bool) {
    if answer == self.valuesArray[self.currentIndex - 1] {
      DispatchQueue.main.async {
        self.showTimeAlertHG("Your answer is Correct")
        self.stopTimer()
        self.captureSession.removeOutput(self.videoOutput)
      }
    }  else {
      DispatchQueue.main.async {
        self.showTimeAlertHG("Your answer is Wrong")
        self.stopTimer()
        self.captureSession.removeOutput(self.videoOutput)
      }
    }

  }

  @objc func updateUIHG() {
    if remainingTime > 0 {
      remainingTime -= 1
      timerLabel.text = "\(remainingTime) seconds"
    } else {
      stopTimer()
      self.captureSession.removeOutput(self.videoOutput)
      showTimeAlertHG("time is up")
    }
  }

  override func showTimeAlertHG(_ message: String) {
    let alert = UIAlertController(title: "Time's up!",
                                message: message,
                                preferredStyle: .alert)
    let action = UIAlertAction(title: "OK", style: .default) { [weak self] _ in
      self?.restartTracking()
      self?.remainingTime = 10
      self?.startTimer()
      self?.updateQuestion()
      self?.timerLabel.text = "10 seconds"
    }
    alert.addAction(action)
    present(alert, animated: true, completion: nil)
  }
}

// MARK: - Extensions -

extension QuestionsViewController: QuestionsViewInterface {
  func getUserData() {
    self.selectedCategory = presenter.getSelectedUserData()
  }
}
