//
//  QuestionsInteractor.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class QuestionsInteractor {
}

// MARK: - Extensions -

extension QuestionsInteractor: QuestionsInteractorInterface {
}
