//
//  QuestionsInterfaces.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol QuestionsWireframeInterface: WireframeInterface {
}

protocol QuestionsViewInterface: ViewInterface {
  func getUserData() 
}

protocol QuestionsPresenterInterface: PresenterInterface {
  func getSelectedUserData() -> Dictionary<String, Bool>
}

protocol QuestionsInteractorInterface: InteractorInterface {
  func fetchData() -> Dictionary<String, Bool> 
}
