//
//  QuestionsPresenter.swift
//  FaceAnswer
//
//  Created by Berkay Unal on 25.01.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class QuestionsPresenter {
    
    // MARK: - Private properties -

    private unowned let view: QuestionsViewInterface
    private let interactor: QuestionsInteractorInterface
    private let wireframe: QuestionsWireframeInterface

    // MARK: - Lifecycle -

    init(view: QuestionsViewInterface, interactor: QuestionsInteractorInterface, wireframe: QuestionsWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension QuestionsPresenter: QuestionsPresenterInterface {
}
